export const types = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGOUT: "LOGOUT",
  AUTH_ERROR: "AUTH_ERROR",
};
